name: nusynth
channels:
  - defaults
  - conda-forge
dependencies:
  - gxx_linux-64=11
  - joblib
  - jupyter
  - matplotlib
  - pandas
  - pip
  - plotly
  - python=3.9
  - scikit-build
  - scikit-learn
  - tbb-devel
  - tensorflow-gpu
  - tqdm
  - pip:
    - kaleido
    - pylatexenc
    - qiskit
